package com.myteam.utarules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NominationResolutions implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u0420\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442 \u0441\u043E\u0433\u043B\u0430\u0441\u043E\u0432\u0430\u043D\u0438\u044F")
	private java.lang.String negotiationResult;
	@org.kie.api.definition.type.Label(value = "\u0424\u043E\u0440\u043C\u0430\u043B\u044C\u043D\u044B\u0439 \u043E\u0442\u0440\u0438\u0446\u0430\u0442\u0435\u043B\u044C\u043D\u044B\u0439 \u0440\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442")
	private java.lang.String negativeReasonType;
	@org.kie.api.definition.type.Label(value = "\u041A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0440\u0438\u0439 \u043A \u043F\u043E\u043B\u043E\u0436\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u043C\u0443 \u0440\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442\u0443")
	private java.lang.String commentPossitiveAnswere;
	@org.kie.api.definition.type.Label(value = "\u041A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0440\u0438\u0439 \u043A \u043D\u0435\u0433\u0430\u0442\u0438\u0432\u043D\u043E\u043C\u0443 \u0440\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442\u0443")
	private java.lang.String commentNegativeAnswere;
	@org.kie.api.definition.type.Label(value = "\u0421\u0442\u0430\u0442\u0443\u0441 \u0441\u043E\u0433\u043B\u0430\u0441\u043E\u0432\u0430\u043D\u0438\u044F \u043D\u043E\u043C\u0438\u043D\u0430\u0446\u0438\u0438")
	private java.lang.String negotiationStatus;

	public NominationResolutions() {
	}

	public java.lang.String getNegotiationResult() {
		return this.negotiationResult;
	}

	public void setNegotiationResult(java.lang.String negotiationResult) {
		this.negotiationResult = negotiationResult;
	}

	public java.lang.String getNegativeReasonType() {
		return this.negativeReasonType;
	}

	public void setNegativeReasonType(java.lang.String negativeReasonType) {
		this.negativeReasonType = negativeReasonType;
	}

	public java.lang.String getCommentPossitiveAnswere() {
		return this.commentPossitiveAnswere;
	}

	public void setCommentPossitiveAnswere(
			java.lang.String commentPossitiveAnswere) {
		this.commentPossitiveAnswere = commentPossitiveAnswere;
	}

	public java.lang.String getCommentNegativeAnswere() {
		return this.commentNegativeAnswere;
	}

	public void setCommentNegativeAnswere(
			java.lang.String commentNegativeAnswere) {
		this.commentNegativeAnswere = commentNegativeAnswere;
	}

	public java.lang.String getNegotiationStatus() {
		return this.negotiationStatus;
	}

	public void setNegotiationStatus(java.lang.String negotiationStatus) {
		this.negotiationStatus = negotiationStatus;
	}

	public NominationResolutions(java.lang.String negotiationResult,
			java.lang.String negativeReasonType,
			java.lang.String commentPossitiveAnswere,
			java.lang.String commentNegativeAnswere,
			java.lang.String negotiationStatus) {
		this.negotiationResult = negotiationResult;
		this.negativeReasonType = negativeReasonType;
		this.commentPossitiveAnswere = commentPossitiveAnswere;
		this.commentNegativeAnswere = commentNegativeAnswere;
		this.negotiationStatus = negotiationStatus;
	}

}