package com.myteam.utarules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Задачи по регистрациии номинаций")
@org.kie.api.definition.type.Description("com.myteam.utarules")
public class Nominations implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Название судна")
	private java.lang.String shipTitle;
	@org.kie.api.definition.type.Label("IMO-номер судна")
	private java.lang.String IMO;
	@org.kie.api.definition.type.Label("Вид груза")
	private java.lang.String cargoType;
	@org.kie.api.definition.type.Label("Предварительный объем груза")
	private java.lang.String cargoAmmount;
	@org.kie.api.definition.type.Label("Дата")
	private java.lang.String firstDate;
	@org.kie.api.definition.type.Label("Клиент")
	private java.lang.String client;
	@org.kie.api.definition.type.Label("Каргоплан")
	private java.lang.String cargoPlan;
	@org.kie.api.definition.type.Label("Планируемая осадка на объем погрузки")
	private java.lang.String planDraughtForCargoAmount;
	@org.kie.api.definition.type.Label("Статус задачи по регистрации номинации")
	private String nominationRegistrationStatus;

	private java.lang.String bildeLoadingPlanFiles;

	public Nominations() {
	}

	public java.lang.String getShipTitle() {
		return this.shipTitle;
	}

	public void setShipTitle(java.lang.String shipTitle) {
		this.shipTitle = shipTitle;
	}

	public java.lang.String getIMO() {
		return this.IMO;
	}

	public void setIMO(java.lang.String IMO) {
		this.IMO = IMO;
	}

	public java.lang.String getCargoType() {
		return this.cargoType;
	}

	public void setCargoType(java.lang.String cargoType) {
		this.cargoType = cargoType;
	}

	public java.lang.String getCargoAmmount() {
		return this.cargoAmmount;
	}

	public void setCargoAmmount(java.lang.String cargoAmmount) {
		this.cargoAmmount = cargoAmmount;
	}

	public java.lang.String getFirstDate() {
		return this.firstDate;
	}

	public void setFirstDate(java.lang.String firstDate) {
		this.firstDate = firstDate;
	}

	public java.lang.String getClient() {
		return this.client;
	}

	public void setClient(java.lang.String client) {
		this.client = client;
	}

	public java.lang.String getCargoPlan() {
		return this.cargoPlan;
	}

	public void setCargoPlan(java.lang.String cargoPlan) {
		this.cargoPlan = cargoPlan;
	}

	public java.lang.String getPlanDraughtForCargoAmount() {
		return this.planDraughtForCargoAmount;
	}

	public void setPlanDraughtForCargoAmount(
			java.lang.String planDraughtForCargoAmount) {
		this.planDraughtForCargoAmount = planDraughtForCargoAmount;
	}

	public java.lang.String getNominationRegistrationStatus() {
		return this.nominationRegistrationStatus;
	}

	public void setNominationRegistrationStatus(
			java.lang.String nominationRegistrationStatus) {
		this.nominationRegistrationStatus = nominationRegistrationStatus;
	}

	public java.lang.String getBildeLoadingPlanFiles() {
		return this.bildeLoadingPlanFiles;
	}

	public void setBildeLoadingPlanFiles(java.lang.String bildeLoadingPlanFiles) {
		this.bildeLoadingPlanFiles = bildeLoadingPlanFiles;
	}

	public Nominations(java.lang.String shipTitle, java.lang.String IMO,
			java.lang.String cargoType, java.lang.String cargoAmmount,
			java.lang.String firstDate, java.lang.String client,
			java.lang.String cargoPlan,
			java.lang.String planDraughtForCargoAmount,
			java.lang.String nominationRegistrationStatus,
			java.lang.String bildeLoadingPlanFiles) {
		this.shipTitle = shipTitle;
		this.IMO = IMO;
		this.cargoType = cargoType;
		this.cargoAmmount = cargoAmmount;
		this.firstDate = firstDate;
		this.client = client;
		this.cargoPlan = cargoPlan;
		this.planDraughtForCargoAmount = planDraughtForCargoAmount;
		this.nominationRegistrationStatus = nominationRegistrationStatus;
		this.bildeLoadingPlanFiles = bildeLoadingPlanFiles;
	}

}